enum GreetIssueType {
  METHODOPPOSITECOMMENT = 'MOP',
  ATTRIBUTEOPPOSITECOMMENT = 'AOP',
  NOTIMPLEMENTEDCONDITION = 'NIC',
  GETMORETHENACCESSOR = 'GET',
  CLEAR = 'CLR',
}

export default GreetIssueType;
